server:
  port: 7001

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    com.bk: debug
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
